# Generated by Django 3.2.19 on 2023-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
