# Generated by Django 3.2.19 on 2023-05-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restuarant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restuarantowner'),
            preserve_default=False,
        ),
    ]
