# Generated by Django 3.2.19 on 2023-06-13 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderitem_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestuarantOwner',
        ),
        migrations.RemoveField(
            model_name='restuarant',
            name='owner',
        ),
        migrations.AddField(
            model_name='restuarant',
            name='manger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restuarantmanager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CUSTOMER', 'Customer'), ('DELIVERY_PERSON', 'Delivery Person')], max_length=50),
        ),
    ]
