# Generated by Django 3.2.19 on 2023-06-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='description',
        ),
        migrations.AlterField(
            model_name='restuarant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='restuarant',
            name='manger',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restuarantmanager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restuarant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restuarant',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CUSTOMER', 'Customer'), ('DELIVERY_PERSON', 'Delivery Person')], default='ADMIN', max_length=50),
        ),
    ]
