# Generated by Django 3.2.19 on 2023-06-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230616_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restuarant',
            old_name='manger',
            new_name='manager',
        ),
    ]
