# Generated by Django 3.2.19 on 2023-06-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_manger_restuarant_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='manager',
        ),
    ]
