# Generated by Django 3.2.19 on 2023-06-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_restuarant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restuarantmanager'),
        ),
    ]
