# Generated by Django 3.2.19 on 2023-06-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_restuarant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarant',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restuarantmanager'),
        ),
    ]
