# Generated by Django 3.2.19 on 2023-06-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_restuarant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
