# Generated by Django 3.2.19 on 2023-06-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_foodcategory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='manager',
        ),
    ]
