# Generated by Django 3.2.19 on 2023-06-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_restuarant_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='manager',
        ),
    ]
