# Generated by Django 3.2.19 on 2023-06-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_restuarant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarant',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.restuarantmanager'),
        ),
    ]
