# Generated by Django 3.2.19 on 2023-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_restuarant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
