# Generated by Django 3.2.19 on 2023-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230621_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_itme',
            new_name='delivering_itme',
        ),
    ]
