# Generated by Django 4.2.2 on 2023-06-24 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_delivery_itme_order_delivering_itme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('success', 'SUCCESS'), ('created', 'CREATED'), ('failed', 'FAILED')], default='created', max_length=50)),
                ('response_dump', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
