# Generated by Django 4.2.2 on 2023-06-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_chapatransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapaTransaction',
        ),
    ]
